name: new_ar_test_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ar_flutter_plugin:
    path: ar_flutter_plugin
  permission_handler: 10.4.5
  shared_preferences: ^2.5.2
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  intl: ^0.19.0 # تم التحديث هنا
  provider: ^6.0.0
  geolocator: ^9.0.0

dependency_overrides:
  permission_handler_android: ^11.1.0
  geolocator_android: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/locales/
    - assets/models/
    - assets/images/
